server.port=8080
logging.level.org.example=DEBUG
logging.level.org.springframework.web=DEBUG
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false

# Enable HTTP methods
spring.mvc.dispatch-options-request=true