package org.example.network.protocol;

public enum RequestType {
    LOGIN,
    LOGOUT,
    REGISTER,
    GET_USER_BY_USERNAME,
    GET_USER_BY_ID,
    GET_ALL_MATCHES,
    GET_MATCH,
    GET_AVAILABLE_TICKETS,
    GET_PRICE_RANGE,
    SELL_TICKETS,
    GET_USER_TICKETS,
    SEARCH_CUSTOMER_TICKETS,
    CHECK_TICKET_SELLER,

    OK, ERROR, MATCH_UPDATED, USER_TICKETS_CHANGED, TICKET_SOLD,
    REGISTER_OBSERVER, UNREGISTER_OBSERVER, START_UPDATE_LISTENER

}